version: '3.7'
services:
  discovery-server:
    build: discovery-server
    image: "simple-cinema/discovery-server"
    container_name: "simple-cinema-discovery-server"
    ports:
      - "8761:8761"
    environment:
      TZ: Canada/Eastern