server:
  port: 8761

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
    numberRegistrySyncRetries: 0
---
spring:
  profiles: docker

  eureka:
    instance:
      hostname: discovery-server
      prefer-ip-address: true
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 30
    client:
      serviceUrl:
        defaultZone: http://discovery-server:8761/eureka/


