server:
  port: 9090
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: docker
eureka:
  instance:
    hostname: admin-server
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/