server:
  port: 9090
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://local:8761/eureka/
---
spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://local:8761/eureka/