server:
  port: 9090
info:
  app:
    name: admin-server
    description: Simple Cinema Application - Admin Server
    version: 0.0.1-SNAPSHOT
---
spring:
  profiles: docker
eureka:
  instance:
    hostname: admin-server