server:
  port: 8000
info:
  app:
    name: api-gateway
    description: Simple Cinema Application - Api Gateway
    version: 0.0.1-SNAPSHOT
---
spring:
  profiles: docker
eureka:
  instance:
    hostname: api-gateway