logging:
  level:
    org.springframework: WARN
    com.netflix: WARN
    io.netty: WARN
    com.simplecinema: DEBUG

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure.include: "*"

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/