server:
  port: 8081
info:
  app:
    name: movie-service
    description: Simple Cinema Application - Movie Service
    version: 0.0.1-SNAPSHOT
---
spring:
  profiles: docker
eureka:
  instance:
    hostname: movie-service