server:
  port: 8081
info:
  app:
    name: movie-service
    description: Simple Cinema Application - Movie Service
    version: 0.0.1-SNAPSHOT
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: docker
eureka:
  instance:
    hostname: movie-service
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/